// fiddles/react/fiddle-0022-TetrisTs/src/components/TetrisGame.tsx
import {
  useCallback,
  useEffect,
  useMemo,
  useReducer,
  useRef,
  useState,
} from 'react'
import {
  COLORS,
  COLS,
  ROWS,
  createInitialState,
  getDisplayBoard,
  levelFor,
  shapeMatrix,
  tetrisReducer,
  tickIntervalMs,
  type Matrix,
  type TetrisAction,
} from '../engine/tetris'
import { useFullscreen } from '../hooks/useFullscreen'
import { useYouTubeBackground } from '../hooks/useYouTubeBackground'
import { buildPreviewSrc, parseYouTubeId } from '../engine/youtube'
import './TetrisGame.css'

const KEY_ACTIONS: Record<string, TetrisAction> = {
  ArrowLeft: { type: 'moveLeft' },
  ArrowRight: { type: 'moveRight' },
  ArrowDown: { type: 'softDrop' },
  ArrowUp: { type: 'rotate' },
  ' ': { type: 'hardDrop' },
  p: { type: 'togglePause' },
  P: { type: 'togglePause' },
}

const cellColor = (cell: number): string =>
  COLORS[(cell - 1) % COLORS.length]

/** Faithful port of the vue fiddle's white→color gradient block. */
function drawBlock(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  bw: number,
  bh: number,
  color: string,
): void {
  const sx = bw * x
  const sy = bh * y
  const grad = ctx.createLinearGradient(sx, sy, sx + bw - 1, sy + bh - 1)
  grad.addColorStop(0, 'white')
  grad.addColorStop(1, color)
  ctx.fillStyle = grad
  ctx.fillRect(sx, sy, Math.max(1, bw - 1), Math.max(1, bh - 1))
}

/** Subtle edge vignette + cyan gridlines, echoing the vue original. */
function drawGrid(
  ctx: CanvasRenderingContext2D,
  w: number,
  h: number,
  bw: number,
  bh: number,
): void {
  const vignette = ctx.createLinearGradient(0, 0, w, h)
  vignette.addColorStop(0, 'rgba(0,0,0,0.35)')
  vignette.addColorStop(0.5, 'rgba(0,0,0,0)')
  vignette.addColorStop(1, 'rgba(0,0,0,0.35)')
  ctx.fillStyle = vignette
  ctx.fillRect(0, 0, w, h)

  ctx.strokeStyle = 'rgba(0, 255, 255, 0.18)'
  ctx.lineWidth = 1
  ctx.beginPath()
  for (let x = 0; x <= w + 0.5; x += bw) {
    ctx.moveTo(x, 0)
    ctx.lineTo(x, h)
  }
  for (let y = 0; y <= h + 0.5; y += bh) {
    ctx.moveTo(0, y)
    ctx.lineTo(w, y)
  }
  ctx.stroke()
}

/** Draw the whole scene onto the transparent canvas over the video. */
function drawScene(
  ctx: CanvasRenderingContext2D,
  w: number,
  h: number,
  board: Matrix,
  gridOn: boolean,
): void {
  ctx.clearRect(0, 0, w, h)
  const bw = w / COLS
  const bh = h / ROWS
  if (gridOn) drawGrid(ctx, w, h, bw, bh)
  for (let y = 0; y < ROWS; y++) {
    for (let x = 0; x < COLS; x++) {
      const cell = board[y][x]
      if (cell) drawBlock(ctx, x, y, bw, bh, cellColor(cell))
    }
  }
}

/** Non-fullscreen container size — the vue original's window formula. */
function computeStageSize(): { w: number; h: number } {
  if (typeof window === 'undefined') return { w: 960, h: 540 }
  return {
    w: Math.max(360, window.innerWidth - 300),
    h: Math.max(240, window.innerHeight - 200),
  }
}

export default function TetrisGame() {
  const [state, dispatch] = useReducer(
    tetrisReducer,
    Date.now() >>> 0,
    createInitialState,
  )
  const gameContainerRef = useRef<HTMLDivElement>(null)
  const canvasRef = useRef<HTMLCanvasElement>(null)

  const { isFullscreen, isSupported, error, toggle } =
    useFullscreen(gameContainerRef)
  const backdrop = useYouTubeBackground()

  const [gridOn, setGridOn] = useState(true)
  const [stage, setStage] = useState(computeStageSize)
  // Actual rendered pixel size of the game container (drives the canvas).
  const [px, setPx] = useState({ w: 0, h: 0 })

  const [dialogOpen, setDialogOpen] = useState(false)
  const [draftUrl, setDraftUrl] = useState('')
  const [dialogError, setDialogError] = useState<string | null>(null)

  const level = levelFor(state.lines)
  const { status } = state

  // --- gravity: one reducer tick per interval, faster each level ------------
  useEffect(() => {
    if (status !== 'playing') return
    const id = setInterval(() => dispatch({ type: 'tick' }), tickIntervalMs(level))
    return () => clearInterval(id)
  }, [status, level])

  // --- keyboard controls -----------------------------------------------------
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null
      // Don't hijack typing in the video-config input.
      if (target && (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA'))
        return
      const action = KEY_ACTIONS[event.key]
      if (!action) return
      event.preventDefault() // keep Space/arrows from scrolling the page
      dispatch(action)
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [])

  // --- non-fullscreen stage size tracks the viewport ------------------------
  useEffect(() => {
    const onResize = () => setStage(computeStageSize())
    window.addEventListener('resize', onResize)
    return () => window.removeEventListener('resize', onResize)
  }, [])

  // --- ResizeObserver: canvas always matches the container's real size ------
  // Fires on mount, on viewport resize, AND on fullscreen enter/exit — the one
  // source of truth for the canvas pixel dimensions, so block size is always
  // recomputed to fill the space.
  useEffect(() => {
    const el = gameContainerRef.current
    if (!el || typeof ResizeObserver === 'undefined') return
    const ro = new ResizeObserver((entries) => {
      const rect = entries[0].contentRect
      setPx({ w: Math.round(rect.width), h: Math.round(rect.height) })
    })
    ro.observe(el)
    return () => ro.disconnect()
  }, [])

  // --- render the transparent canvas over the video -------------------------
  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas || px.w === 0 || px.h === 0) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return
    const dpr = Math.min(window.devicePixelRatio || 1, 2)
    const w = Math.max(1, Math.round(px.w * dpr))
    const h = Math.max(1, Math.round(px.h * dpr))
    if (canvas.width !== w) canvas.width = w
    if (canvas.height !== h) canvas.height = h
    drawScene(ctx, w, h, getDisplayBoard(state), gridOn)
  }, [state, px, gridOn])

  // --- handlers --------------------------------------------------------------
  const start = useCallback(
    () => dispatch({ type: 'start', seed: Date.now() >>> 0 }),
    [],
  )
  const blurThen = (fn: () => void) => (e: React.MouseEvent<HTMLButtonElement>) => {
    e.currentTarget.blur() // Space/arrows should drive the game, not re-click
    fn()
  }

  const openDialog = () => {
    setDraftUrl(backdrop.videoId)
    setDialogError(null)
    setDialogOpen(true)
  }
  const confirmVideo = () => {
    const id = backdrop.setFromInput(draftUrl)
    if (!id) {
      setDialogError('Could not find a YouTube video id in that input.')
      return
    }
    setDialogOpen(false)
  }
  const resetVideo = () => {
    backdrop.reset()
    setDialogOpen(false)
  }

  const nextPiece = useMemo(
    () => shapeMatrix(state.nextPieceId),
    [state.nextPieceId],
  )
  const previewId = parseYouTubeId(draftUrl) ?? backdrop.videoId
  const canPause = status === 'playing' || status === 'paused'

  return (
    <div className="tetris-root">
      <div
        className="game-container"
        ref={gameContainerRef}
        style={isFullscreen ? undefined : { width: stage.w, height: stage.h }}
      >
        {/* YouTube backdrop — sits BEHIND the transparent canvas (z-index). */}
        <div className="video-wrapper">
          <iframe
            title="YouTube background"
            className="youtube-background"
            src={backdrop.embedSrc}
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
          />
        </div>

        {/* The game is drawn here; empty cells stay transparent so the video reads. */}
        <canvas ref={canvasRef} className="game-canvas" aria-label="Tetris board" />

        {/* HUD overlay — always visible, including in fullscreen. */}
        <div className="hud">
          <div className="hud-brand">TETRIS</div>
          <div className="hud-stats">
            <div className="hud-item">
              <span className="hud-label">Score</span>
              <span className="hud-value">{state.score}</span>
            </div>
            <div className="hud-item">
              <span className="hud-label">Lines</span>
              <span className="hud-value">{state.lines}</span>
            </div>
            <div className="hud-item">
              <span className="hud-label">Level</span>
              <span className="hud-value">{level}</span>
            </div>
          </div>
          <div className="hud-next">
            <span className="hud-label">Next</span>
            <div className="next-grid">
              {nextPiece.flatMap((row, y) =>
                row.map((cell, x) => (
                  <span
                    key={`${y}:${x}`}
                    className="next-cell"
                    style={cell ? { backgroundColor: cellColor(cell) } : undefined}
                  />
                )),
              )}
            </div>
          </div>
        </div>

        {/* Center status overlay for idle / paused / game-over. */}
        {status !== 'playing' && (
          <div className="status-overlay">
            {status === 'idle' && <p className="status-title">TETRIS</p>}
            {status === 'paused' && <p className="status-title">Paused</p>}
            {status === 'gameover' && (
              <>
                <p className="status-title">Game Over</p>
                <p className="status-detail">Score {state.score}</p>
              </>
            )}
            <button
              type="button"
              className="status-button"
              onClick={blurThen(
                status === 'paused'
                  ? () => dispatch({ type: 'togglePause' })
                  : start,
              )}
            >
              {status === 'idle'
                ? 'Start'
                : status === 'paused'
                  ? 'Resume'
                  : 'Play Again'}
            </button>
          </div>
        )}

        {/* Control bar — overlays the board, stays reachable in fullscreen. */}
        <div className="control-bar">
          <div className="control-group dpad">
            <button
              type="button"
              title="Left"
              disabled={status !== 'playing'}
              onClick={blurThen(() => dispatch({ type: 'moveLeft' }))}
            >
              ◀
            </button>
            <button
              type="button"
              title="Rotate"
              disabled={status !== 'playing'}
              onClick={blurThen(() => dispatch({ type: 'rotate' }))}
            >
              ▲
            </button>
            <button
              type="button"
              title="Soft drop"
              disabled={status !== 'playing'}
              onClick={blurThen(() => dispatch({ type: 'softDrop' }))}
            >
              ▼
            </button>
            <button
              type="button"
              title="Right"
              disabled={status !== 'playing'}
              onClick={blurThen(() => dispatch({ type: 'moveRight' }))}
            >
              ▶
            </button>
            <button
              type="button"
              title="Hard drop (Space)"
              disabled={status !== 'playing'}
              onClick={blurThen(() => dispatch({ type: 'hardDrop' }))}
            >
              ⤓
            </button>
          </div>

          <div className="control-group">
            <button type="button" onClick={blurThen(start)}>
              {status === 'idle' ? 'Start' : 'Restart'}
            </button>
            <button
              type="button"
              disabled={!canPause}
              onClick={blurThen(() => dispatch({ type: 'togglePause' }))}
            >
              {status === 'paused' ? 'Resume' : 'Pause'}
            </button>
            <button
              type="button"
              className={gridOn ? 'active' : ''}
              title="Toggle gridlines"
              onClick={blurThen(() => setGridOn((g) => !g))}
            >
              {gridOn ? 'Grid ✓' : 'Grid'}
            </button>
            <button type="button" title="Change background video" onClick={openDialog}>
              Video
            </button>
            <button
              type="button"
              disabled={!isSupported}
              title={isSupported ? 'Toggle fullscreen' : 'Fullscreen unavailable'}
              onClick={blurThen(() => void toggle())}
            >
              {isFullscreen ? 'Exit Fullscreen' : 'Fullscreen'}
            </button>
          </div>
        </div>

        {(!isSupported || error) && (
          <p className="fullscreen-note" role="status">
            {!isSupported
              ? 'Fullscreen is not available in this browser.'
              : error}
          </p>
        )}
      </div>

      {/* Configurable-video dialog. */}
      {dialogOpen && (
        <div
          className="dialog-backdrop"
          onClick={(e) => {
            if (e.target === e.currentTarget) setDialogOpen(false)
          }}
        >
          <div className="dialog" role="dialog" aria-label="Change background video">
            <h2>Change background video</h2>
            <input
              type="text"
              value={draftUrl}
              placeholder="Paste a YouTube URL or video id"
              onChange={(e) => {
                setDraftUrl(e.target.value)
                setDialogError(null)
              }}
              onKeyDown={(e) => {
                if (e.key === 'Enter') confirmVideo()
              }}
            />
            <div className="dialog-preview">
              <iframe
                title="Video preview"
                src={buildPreviewSrc(previewId)}
                frameBorder="0"
                allow="encrypted-media; picture-in-picture"
              />
            </div>
            {dialogError && <p className="dialog-error">{dialogError}</p>}
            <div className="dialog-buttons">
              <button type="button" onClick={resetVideo}>
                Reset to default
              </button>
              <button type="button" onClick={() => setDialogOpen(false)}>
                Cancel
              </button>
              <button type="button" className="primary" onClick={confirmVideo}>
                Confirm
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// fiddles/angular/fiddle-0041-TetrisTs/src/app/tetris/tetris-game.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostListener,
  computed,
  effect,
  inject,
  signal,
  viewChild,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  COLORS,
  COLS,
  GameState,
  ROWS,
  hardDrop,
  initialState,
  levelFor,
  moveLeft,
  moveRight,
  newGame,
  rotatePiece,
  softDrop,
  tick,
  tickIntervalMs,
  togglePause,
} from '../engine/tetris';
import { DEFAULT_VIDEO_ID } from '../engine/youtube';
import { FullscreenService } from '../fullscreen/fullscreen.service';
import { VideoService } from '../video/video.service';

/**
 * Presentation shell around the pure engine — faithful to the vue original's
 * character:
 *   - a WIDE, landscape canvas sized to the viewport (and re-sized on resize /
 *     fullscreen), block size recomputed to fill the space,
 *   - a YouTube <iframe> backdrop behind a TRANSPARENT canvas so the video
 *     shows through the empty cells while you play,
 *   - a configurable backdrop (paste a URL or bare id) + a gridline toggle.
 *
 * The whole game lives in one `signal<GameState>`; every input applies an engine
 * transition via `state.update(...)`. Derived values (score/level/speed) are
 * `computed`; the gravity loop is an `effect` that re-schedules its interval
 * whenever the level-driven speed changes; a second `effect` redraws the canvas
 * whenever the state, grid toggle, or viewport size changes. OnPush throughout.
 */
@Component({
  selector: 'app-tetris-game',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule],
  templateUrl: './tetris-game.component.html',
  styleUrl: './tetris-game.component.css',
})
export class TetrisGameComponent {
  private readonly fullscreen = inject(FullscreenService);
  protected readonly video = inject(VideoService);

  /** Fullscreen target: the stage wrapping BOTH the iframe and the canvas. */
  private readonly stage = viewChild.required<ElementRef<HTMLElement>>('stage');
  private readonly canvasRef = viewChild<ElementRef<HTMLCanvasElement>>('canvas');

  protected readonly state = signal<GameState>(initialState());

  protected readonly status = computed(() => this.state().status);
  protected readonly score = computed(() => this.state().score);
  protected readonly lines = computed(() => this.state().lines);
  protected readonly level = computed(() => levelFor(this.lines()));
  protected readonly speedMs = computed(() => tickIntervalMs(this.level()));

  /** Landscape canvas size in CSS pixels; recomputed on resize / fullscreen. */
  protected readonly viewW = signal(960);
  protected readonly viewH = signal(540);

  protected readonly gridOn = signal(true);

  // Configurable-video panel state.
  protected readonly showVideoPanel = signal(false);
  protected readonly draftUrl = signal<string>(DEFAULT_VIDEO_ID);
  protected readonly videoError = signal<string | null>(null);
  protected readonly previewUrl = computed(() => this.video.previewUrl(this.draftUrl()));

  protected readonly isFullscreen = this.fullscreen.isFullscreen;
  protected readonly fullscreenError = this.fullscreen.error;

  constructor() {
    this.recompute();

    // Render loop: redraw whenever the state, grid toggle, or size changes.
    effect(() => {
      const canvas = this.canvasRef()?.nativeElement;
      if (!canvas) return;
      const w = this.viewW();
      const h = this.viewH();
      if (canvas.width !== w) canvas.width = w;
      if (canvas.height !== h) canvas.height = h;
      this.draw(canvas, this.state(), this.gridOn(), w, h);
    });

    // Gravity loop: runs only while playing; torn down and re-created at the new
    // interval when the level (hence speed) changes.
    effect((onCleanup) => {
      if (this.status() !== 'playing') return;
      const timer = setInterval(() => this.state.update((s) => tick(s)), this.speedMs());
      onCleanup(() => clearInterval(timer));
    });
  }

  // ---- input -------------------------------------------------------------

  @HostListener('window:keydown', ['$event'])
  protected onKeydown(event: KeyboardEvent): void {
    const target = event.target as HTMLElement | null;
    if (target && (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA')) return;

    switch (event.key) {
      case 'ArrowLeft':
        event.preventDefault();
        this.state.update(moveLeft);
        break;
      case 'ArrowRight':
        event.preventDefault();
        this.state.update(moveRight);
        break;
      case 'ArrowDown':
        event.preventDefault();
        this.state.update(softDrop);
        break;
      case 'ArrowUp':
        event.preventDefault();
        this.state.update(rotatePiece);
        break;
      case ' ':
        event.preventDefault();
        this.state.update((s) => hardDrop(s));
        break;
      case 'p':
      case 'P':
        this.state.update(togglePause);
        break;
    }
  }

  @HostListener('window:resize')
  @HostListener('document:fullscreenchange')
  @HostListener('document:webkitfullscreenchange')
  protected recompute(): void {
    const fs = this.inFullscreen();
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    if (fs) {
      this.viewW.set(vw);
      this.viewH.set(vh);
      return;
    }
    // Wide landscape, sized to the viewport; keep a 16:9 field with near-square
    // blocks, shrinking to fit whichever of width/height is the binding limit.
    let w = Math.max(360, Math.min(vw - 40, 1400));
    let h = Math.round((w * ROWS) / COLS);
    const maxH = Math.max(240, vh - 140);
    if (h > maxH) {
      h = maxH;
      w = Math.round((h * COLS) / ROWS);
    }
    this.viewW.set(w);
    this.viewH.set(h);
  }

  private inFullscreen(): boolean {
    const doc = document as Document & { webkitFullscreenElement?: Element | null };
    return Boolean(doc.fullscreenElement ?? doc.webkitFullscreenElement);
  }

  // ---- game controls -----------------------------------------------------

  protected start(): void {
    this.state.set(newGame());
  }

  protected pause(): void {
    this.state.update(togglePause);
  }

  protected move(dir: 'left' | 'right' | 'down' | 'rotate' | 'drop'): void {
    switch (dir) {
      case 'left':
        this.state.update(moveLeft);
        break;
      case 'right':
        this.state.update(moveRight);
        break;
      case 'down':
        this.state.update(softDrop);
        break;
      case 'rotate':
        this.state.update(rotatePiece);
        break;
      case 'drop':
        this.state.update((s) => hardDrop(s));
        break;
    }
  }

  protected toggleGrid(): void {
    this.gridOn.update((on) => !on);
  }

  protected async toggleFullscreen(): Promise<void> {
    await this.fullscreen.toggle(this.stage().nativeElement);
  }

  // ---- configurable video ------------------------------------------------

  protected openVideoPanel(): void {
    this.draftUrl.set(this.video.videoId());
    this.videoError.set(null);
    this.showVideoPanel.set(true);
  }

  protected closeVideoPanel(): void {
    this.showVideoPanel.set(false);
  }

  protected applyVideo(): void {
    const id = this.video.set(this.draftUrl());
    if (!id) {
      this.videoError.set('Could not find a YouTube video id in that input.');
      return;
    }
    this.videoError.set(null);
    this.showVideoPanel.set(false);
  }

  protected resetVideo(): void {
    this.video.reset();
    this.draftUrl.set(DEFAULT_VIDEO_ID);
    this.videoError.set(null);
  }

  // ---- canvas rendering --------------------------------------------------

  private draw(canvas: HTMLCanvasElement, state: GameState, gridOn: boolean, w: number, h: number): void {
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    const bw = w / COLS;
    const bh = h / ROWS;

    ctx.clearRect(0, 0, w, h);
    if (gridOn) this.drawGrid(ctx, w, h, bw, bh);

    const { board, piece, status } = state;
    for (let y = 0; y < ROWS; y++) {
      for (let x = 0; x < COLS; x++) {
        const v = board[y][x];
        if (v) this.drawBlock(ctx, x, y, bw, bh, COLORS[(v - 1) % COLORS.length]);
      }
    }

    if (status === 'playing' || status === 'paused') {
      piece.matrix.forEach((row, py) =>
        row.forEach((v, px) => {
          if (v) this.drawBlock(ctx, piece.x + px, piece.y + py, bw, bh, COLORS[(v - 1) % COLORS.length]);
        }),
      );
    }
  }

  private drawGrid(ctx: CanvasRenderingContext2D, w: number, h: number, bw: number, bh: number): void {
    // Subtle vignette so the field edges read against the video (echoes the
    // original's black→transparent→black grid gradient, but lighter).
    const vignette = ctx.createLinearGradient(0, 0, w, h);
    vignette.addColorStop(0, 'rgba(0, 0, 0, 0.45)');
    vignette.addColorStop(0.5, 'rgba(0, 0, 0, 0)');
    vignette.addColorStop(1, 'rgba(0, 0, 0, 0.45)');
    ctx.fillStyle = vignette;
    ctx.fillRect(0, 0, w, h);

    ctx.strokeStyle = 'rgba(0, 255, 255, 0.22)';
    ctx.lineWidth = 1;
    for (let x = 0; x <= COLS; x++) {
      const px = Math.round(x * bw) + 0.5;
      ctx.beginPath();
      ctx.moveTo(px, 0);
      ctx.lineTo(px, h);
      ctx.stroke();
    }
    for (let y = 0; y <= ROWS; y++) {
      const py = Math.round(y * bh) + 0.5;
      ctx.beginPath();
      ctx.moveTo(0, py);
      ctx.lineTo(w, py);
      ctx.stroke();
    }
  }

  private drawBlock(
    ctx: CanvasRenderingContext2D,
    x: number,
    y: number,
    bw: number,
    bh: number,
    color: string,
  ): void {
    const sx = x * bw;
    const sy = y * bh;
    const cw = Math.max(1, bw - 1);
    const ch = Math.max(1, bh - 1);

    const gradient = ctx.createLinearGradient(sx, sy, sx + cw, sy + ch);
    gradient.addColorStop(0, '#ffffff');
    gradient.addColorStop(1, color);
    ctx.fillStyle = gradient;
    ctx.fillRect(sx, sy, cw, ch);

    ctx.strokeStyle = 'rgba(0, 0, 0, 0.28)';
    ctx.lineWidth = 1;
    ctx.strokeRect(sx + 0.5, sy + 0.5, cw, ch);
  }
}

<div
  #stage
  class="stage"
  [class.is-fullscreen]="isFullscreen()"
  [style.width.px]="viewW()"
  [style.height.px]="viewH()"
>
  <!-- YouTube backdrop: sits BEHIND a transparent canvas so the video shows
       through the empty cells while you play. -->
  <div class="video-wrapper">
    <iframe
      class="youtube-backdrop"
      title="YouTube video backdrop"
      [src]="video.embedUrl()"
      frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen
    ></iframe>
  </div>

  <!-- Transparent playfield: only filled blocks + optional gridlines are drawn. -->
  <canvas #canvas class="playfield" [width]="viewW()" [height]="viewH()"></canvas>

  <!-- HUD -->
  <header class="hud" aria-label="Game stats">
    <div class="stat">
      <span class="stat-label">Score</span>
      <span class="stat-value">{{ score() }}</span>
    </div>
    <div class="stat">
      <span class="stat-label">Lines</span>
      <span class="stat-value">{{ lines() }}</span>
    </div>
    <div class="stat">
      <span class="stat-label">Level</span>
      <span class="stat-value">{{ level() }}</span>
    </div>
    <div class="stat">
      <span class="stat-label">Speed</span>
      <span class="stat-value">{{ speedMs() }}<small>ms</small></span>
    </div>
  </header>

  <!-- Status overlays -->
  @if (status() === 'idle') {
    <div class="overlay">
      <p class="overlay-title">Tetris</p>
      <p class="overlay-hint">press Start to play over the video</p>
    </div>
  } @else if (status() === 'paused') {
    <div class="overlay">
      <p class="overlay-title">Paused</p>
      <p class="overlay-hint">press P to resume</p>
    </div>
  } @else if (status() === 'over') {
    <div class="overlay">
      <p class="overlay-title">Game over</p>
      <p class="overlay-hint">final score {{ score() }} — press Restart</p>
    </div>
  }

  <!-- Control bar -->
  <footer class="controls" aria-label="Game controls">
    <div class="pad" role="group" aria-label="Move">
      <button type="button" title="Move left (←)" (click)="move('left')">◀</button>
      <button type="button" title="Rotate (↑)" (click)="move('rotate')">⟳</button>
      <button type="button" title="Soft drop (↓)" (click)="move('down')">▼</button>
      <button type="button" title="Move right (→)" (click)="move('right')">▶</button>
      <button type="button" title="Hard drop (space)" (click)="move('drop')">⤓</button>
    </div>

    <div class="group" role="group" aria-label="Game">
      <button type="button" (click)="start()">{{ status() === 'idle' ? 'Start' : 'Restart' }}</button>
      <button
        type="button"
        (click)="pause()"
        [disabled]="status() === 'idle' || status() === 'over'"
      >
        {{ status() === 'paused' ? 'Resume' : 'Pause' }}
      </button>
    </div>

    <div class="group" role="group" aria-label="View">
      <button type="button" (click)="toggleGrid()" [class.on]="gridOn()">
        {{ gridOn() ? 'Grid on' : 'Grid off' }}
      </button>
      <button type="button" (click)="openVideoPanel()">Video</button>
      <button type="button" (click)="toggleFullscreen()">
        {{ isFullscreen() ? 'Exit fullscreen' : 'Fullscreen' }}
      </button>
    </div>
  </footer>

  <!-- Configurable backdrop panel -->
  @if (showVideoPanel()) {
    <div class="video-panel" role="dialog" aria-label="Change background video">
      <p class="panel-title">Background video</p>
      <input
        type="text"
        class="panel-input"
        placeholder="YouTube URL or 11-char video id"
        [ngModel]="draftUrl()"
        (ngModelChange)="draftUrl.set($event)"
        (keydown.enter)="applyVideo()"
      />

      @if (previewUrl(); as preview) {
        <iframe
          class="panel-preview"
          title="Video preview"
          [src]="preview"
          frameborder="0"
          allow="autoplay; encrypted-media"
        ></iframe>
      } @else {
        <p class="panel-hint">Paste a watch/share/embed URL or a bare id to preview.</p>
      }

      @if (videoError(); as message) {
        <p class="panel-error" role="alert">{{ message }}</p>
      }

      <div class="panel-buttons">
        <button type="button" (click)="resetVideo()">Reset to default</button>
        <span class="spacer"></span>
        <button type="button" (click)="closeVideoPanel()">Cancel</button>
        <button type="button" class="primary" (click)="applyVideo()">Apply</button>
      </div>
    </div>
  }

  @if (fullscreenError(); as message) {
    <p class="fullscreen-error" role="alert">{{ message }}</p>
  }
</div>

<p class="key-legend">
  &larr; &rarr; move &middot; &uarr; rotate &middot; &darr; soft drop &middot; space hard drop &middot; P pause
</p>
