// fiddles/angular/template/src/app/components/doc-list/doc-list-item.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule, NgIf } from '@angular/common';

@Component({
  selector: 'app-doc-list-item',
  standalone: true,
  template: `
    <div class="item">
      <div class="item-icon">
        <ng-template #iconContent>
          <ng-content select="[icon]"></ng-content>
        </ng-template>
      </div>
      <ng-container *ngIf="iconHref; else noIconHref">
        <i>
          <a href="{{iconHref}}" target="_blank" rel="noopener">
            <ng-container *ngTemplateOutlet="iconContent"></ng-container>
          </a>
        </i>
      </ng-container>

      <ng-template #noIconHref>
        <i>
          <ng-container *ngTemplateOutlet="iconContent"></ng-container>
        </i>
      </ng-template>

      <div class="details">
        <h3 style="color: black">
          <ng-content select="[heading]"></ng-content>
        </h3>
        <div>
          <ng-content></ng-content>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .item {
      margin-top: 2rem;
      display: flex;
    }

    .item-icon{
      --color-background: #2c3e50 !important;
      color: white !important;
      transition: none !important;
    }

    .item-icon:hover {
      --color-background: #2c3e50 !important;
      color: white !important;
      transition: none !important;
    }
    
    .details {
      flex: 1;
      margin-left: 1rem;
    }

    i {
      display: flex;
      place-items: center;
      place-content: center;
      width: 32px;
      height: 32px;
      color: #2c3e50;
      --color-background: white;
      cursor: pointer;
    }

    a {
      --color-background: #2c3e50 !important;
      cursor: pointer !important;
    }

    
    a:hover,
    i:hover {
      --color-background: #2c3e50 !important;
      color: white !important;
      transition: none !important;
    }

    h3 {
      font-size: 1.2rem;
      font-weight: 500;
      margin-bottom: 0.4rem;
      color: #2c3e50;
    }

    @media (min-width: 500px) {
      .item {
        margin-top: 0;
        padding: 0.4rem 0 1rem calc(var(--section-gap) / 2);
      }

      i {
        top: calc(50% - 25px);
        left: -26px;
        position: absolute;
        border: 1px solid var(--color-border);
        background: var(--color-background);
        border-radius: 8px;
        width: 50px;
        height: 50px;
      }

      .item:before {
        content: ' ';
        border-left: 1px solid var(--color-border);
        position: absolute;
        left: 0;
        bottom: calc(50% + 25px);
        height: calc(50% - 25px);
      }

      .item:after {
        content: ' ';
        border-left: 1px solid var(--color-border);
        position: absolute;
        left: 0;
        top: calc(50% + 25px);
        height: calc(50% - 25px);
      }

      .item:first-of-type:before {
        display: none;
      }

      .item:last-of-type:after {
        display: none;
      }
    }
  `],
  imports: [CommonModule, NgIf]
})
export class DocListItemComponent {
  @Input() iconHref?: string;
}

// fiddles/vue/fiddle-0018-InfiniteSelectJs/src/components/DocListItem.vue
<template>
  <div class="item">
    <i>
      <slot name="icon"></slot>
    </i>
    <div class="details">
      <h3 style="color: black">
        <slot name="heading"></slot>
      </h3>
      <slot></slot>
    </div>
  </div>
</template>

<style scoped>
.item {
  margin-top: 1rem;
  display: flex;
}

.details {
  flex: 1;
  margin-top: 1rem;
  margin-left: 1rem;
}

i {
  display: flex;
  place-items: center;
  place-content: center;
  width: 32px;
  height: 32px;

  color: var(--color-text);
}

h3 {
  font-size: 1.2rem;
  font-weight: 500;
  margin-bottom: 0.4rem;
  color: var(--color-heading);
}

@media (min-width: 500px) {
  .item {
    margin-top: 0;
    padding: 0.4rem 0 1rem calc(var(--section-gap) / 2);
  }

  i {
    top: calc(50% - 25px);
    left: -26px;
    position: absolute;
    border: 1px solid var(--color-border);
    background: var(--color-background);
    border-radius: 8px;
    width: 50px;
    height: 50px;
  }

  .item:before {
    content: ' ';
    border-left: 1px solid var(--color-border);
    position: absolute;
    left: 0;
    bottom: calc(50% + 25px);
    height: calc(50% - 25px);
  }

  .item:after {
    content: ' ';
    border-left: 1px solid var(--color-border);
    position: absolute;
    left: 0;
    top: calc(50% + 25px);
    height: calc(50% - 25px);
  }

  .item:first-of-type:before {
    display: none;
  }

  .item:last-of-type:after {
    display: none;
  }
}
</style>
