// fiddles/angular/fiddle-0036-EntAgGridToolTips/src/main.ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import { LicenseManager } from '@ag-grid-enterprise/all-modules';


fetch('assets/license.json').then((response: any) => {
  return response.json();
}).then((data: any) => {
  LicenseManager.setLicenseKey(data.license);
  if (environment.production) {
    enableProdMode();
  }
  platformBrowserDynamic().bootstrapModule(AppModule)
    .catch(err => console.error(err));
});

// fiddles/react/fiddle-0017-EnterpriseAgGrid/src/index.js
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.bundle.min';
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './app/App';
import reportWebVitals from './reportWebVitals';
import { LicenseManager } from 'ag-grid-enterprise';


fetch('resources.json').then((response) => {
  return response.json();
}).then((data) => {
  LicenseManager.setLicenseKey(data.license);
  ReactDOM.render(
    <React.StrictMode>
      <App />
    </React.StrictMode>,
    document.getElementById('root')
  );
});



reportWebVitals(console.log);
