// fiddles/vue/fiddle-0017-VeeValidateVueSelectJs/src/views/AboutView.vue
<template>
  <div v-html="markdownToHtml"></div>
</template>

<script>
import { marked } from 'marked'

export default {
  name: 'AboutView',
  data() {
    return {
      content: 'loading ...'
    }
  },
  mounted() {
    const origin = window.location.origin
    const pathName = window.location.pathname.replace('/about', '')
    const url = 'README.md'
    fetch(url)
      .then((response) => response.text())
      .then((text) => this.bindText(text))
  },
  components: {},
  computed: {
    markdownToHtml() {
      return marked.parse(this.content)
    }
  },
  methods: {
    bindText(text) {
      console.log(text)
      this.content = text
    }
  }
}
</script>

<style scoped>
div {
  padding: 1rem;
}
@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>

// fiddles/angular/template/src/app/views/about-view/about-view.component.ts
import { Component, OnInit } from '@angular/core';
import { marked } from 'marked';

@Component({
  selector: 'app-about-view',
  templateUrl: './about-view.component.html',
  styleUrls: ['./about-view.component.css']
})
export class AboutViewComponent implements OnInit {
  
  content:any = 'Loading...';

  constructor() { }

  ngOnInit() {
    this.fetchContent();
  }

  async fetchContent() {
    const origin = window.location.origin;
    const pathName = window.location.pathname.replace('/about', '');
    const url = 'README.md';
    
    try {
      const response = await fetch(url);
      const text = await response.text();
      this.content = marked.parse(text);
    } catch (error) {
      console.error('Error fetching content:', error);
    }
  }
}
